# Generated by Django 5.2.6 on 2025-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.CharField(choices=[('tanphu', 'Quận Tân Phú'), ('binhtan', 'Quận Bình Tân'), ('govap', 'Quận Gò Vấp'), ('quan12', 'Quận 12'), ('quan1', 'Quận 1'), ('quan3', 'Quận 3'), ('quan5', 'Quận 5'), ('quan7', 'Quận 7'), ('binhthanh', 'Quận Bình Thạnh'), ('tphcm', 'TP. Hồ Chí Minh (khác)')], default='tphcm', max_length=50, verbose_name='Quận/Huyện'),
        ),
    ]
