# Generated by Django 5.2.6 on 2025-09-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_options_product_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Danh sách sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='district',
        ),
    ]
