# Generated by Django 5.2.6 on 2025-09-21 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Admin')], max_length=10)),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn trực tiếp',
                'verbose_name_plural': 'Hộp thoại trực tiếp',
                'ordering': ['created_at'],
            },
        ),
    ]
