# Generated by Django 5.2.6 on 2025-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_directchatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat AI', 'verbose_name_plural': 'Lịch sử chat AI'},
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Tin nhắn'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, verbose_name='Phản hồi AI'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Admin')], max_length=10, verbose_name='Người gửi'),
        ),
    ]
