# Generated by Django 5.2.6 on 2025-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_chatmessage_options_directchatmessage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Danh sách video',
                'ordering': ['-created_at'],
            },
        ),
    ]
