# Generated by Django 5.2.6 on 2025-09-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_video_url_alter_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='products/videos/', verbose_name='Video sản phẩm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.product')),
            ],
            options={
                'verbose_name': 'Video sản phẩm',
                'verbose_name_plural': 'Danh sách video sản phẩm',
            },
        ),
    ]
