# Generated by Django 5.2.6 on 2025-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_customer_created_at_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người bình luận'),
        ),
    ]
