# Generated by Django 5.2.6 on 2025-10-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_comment_name'),
    ]

    operations = [
    ]
