# Generated by Django 5.2.6 on 2025-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20251016_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.CharField(choices=[('Tân Phú', 'Tân Phú'), ('Bình Tân', 'Bình Tân'), ('Tân Bình', 'Tân Bình'), ('Gò Vấp', 'Gò Vấp'), ('Quận 1', 'Quận 1'), ('Quận 3', 'Quận 3'), ('Phú Nhuận', 'Phú Nhuận'), ('Bình Thạnh', 'Bình Thạnh')], default='Tân Phú', max_length=100, verbose_name='Quận'),
        ),
    ]
