# Generated by Django 5.2.6 on 2025-11-01 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_directchatmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directchatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn trực tiếp', 'verbose_name_plural': 'Hộp thoại trực tiếp'},
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Admin')], max_length=10, verbose_name='Người gửi'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
