# Generated by Django 5.2.6 on 2025-11-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_directchatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={},
        ),
    ]
